### ISSUE TITLE
Documentation build fails on crates.io

### ISSUE THREAD

**Issue by danielSanchezQ** [waku-org/waku-rust-bindings#24]
https://docs.rs/crate/waku-bindings/0.1.0-beta1/builds

**Comment by danielSanchezQ** [comment]
Looks like go tries to write to some folder we have no access to:

`[INFO] [stderr]   failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied`

**Comment by danielSanchezQ** [comment]
@richard-ramos any idea that folder can be changed somehow?

**Comment by richard-ramos** [comment]
Can we try setting this environment variable: `GOCACHE=/tmp/`

**Comment by chair28980** [comment]
It appears the docs cannot be built when you do not have access to the go runtime environment: https://docs.rs/crate/waku-bindings/0.4.0/builds/1012533
