### ISSUE TITLE
Peer discovery & management 

### ISSUE THREAD

**Issue by hopeyen** [waku-org/waku-rust-bindings#52]
At the moment, enabling DiscV5 mechanism requires multiaddresses upon node handle initialization, while DNS discovery takes enrtree url and resolves to multiaddresses after node initialization. 

It would be nice if the two mechanisms are consistent, potentially
1. DiscV5 can be initialized with a ENRtree url instead of a set of multiaddresses
2. DiscV5 can be enabled after the initialization of the node
3. Or if an ENRtree url can be optionally supplied with a toggle for discovery mechanisms, between static list, DNS discovery, DiscV5, ...

A potential flow is
1. Initialize waku node, use DNS url to get bootstrap nodes
2. Connect to bootstrap nodes either by DNS discovery or enable DiscV5
3. Remember "good" peers to use in DiscV5 when node gets restarted

**Comment by richard-ramos** [comment]
**Weekly Update**

- _achieved_: Added dns discovery parameters to the node config
