### ISSUE TITLE
Crate is to big to be uploaded to crates.io

### ISSUE THREAD

**Issue by danielSanchezQ** [waku-org/waku-rust-bindings#55]
We need to filter out unnecessary go source code from the `vendor` folder.
@fryorcraken took a look and the `coverage` forlder is the one to strip out as a lower hanging fruit, but other stuff may be taken away as well.

```
▶ du -sh * |sort -h
4.0K    CHANGELOG.md
4.0K    Dockerfile
4.0K    LICENSE-MIT
4.0K    pkg
4.0K    VERSION
8.0K    go.mod
8.0K    hooks
8.0K    Makefile
8.0K    README.md
12K    LICENSE-APACHEv2
16K    build
24K    logging
28K    ci
28K    scripts
28K    tests
40K    cmd
64K    mobile
68K    library
192K    docs
244K    go.sum
1.3M    examples
1.5M    waku
13M    coverage
```

**Comment by danielSanchezQ** [comment]
It should be possible to do it with the `exclude` attribute in the `[package]` section on the `Cargo.toml` file:

```toml
[package]
exclude = ["..."]
```

**Comment by richard-ramos** [comment]
This should be fixed already
