### ISSUE TITLE
bug: gowaku.node log cannot be turned off

### ISSUE THREAD

**Issue by hopeyen** [waku-org/waku-rust-bindings#56]
We would like to reduce the amount of logs coming from the waku nodes, but the log level [options](https://github.com/waku-org/waku-rust-bindings/blob/27597d76b53cfe166285cd1c449ec4278a95a2e4/waku-bindings/src/node/config.rs#L58) aren't effective  

Previous [fix](https://github.com/waku-org/go-waku/commit/cedaa670c75b74990571248edbd83dc445c99bac)
Discord [discussion](https://discord.com/channels/864066763682218004/956692465593774112/1083495182244266006)

**Comment by bacv** [comment]
We've previously added these test cases to verify that log level options are effective (https://github.com/waku-org/waku-rust-bindings/blob/27597d76b53cfe166285cd1c449ec4278a95a2e4/waku-bindings/tests/node.rs#L300). Could you paste the config that is not working for you?

**Comment by hopeyen** [comment]
Has the fix gone through a crate release yet?
We are using the rust tracing crate for setting log levels, but it cannot manage log coming from gowaku node. 
```
let filter = EnvFilter::from_default_env();
let subscriber = FmtSubscriber::builder()
    .with_env_filter(filter)
    .with_ansi(true)
    .with_target(true)
    .with_level(true)
    .with_line_number(true)
    .pretty()
    .finish();
tracing::subscriber::set_global_default(subscriber)
```
Also have additional handling but INFO log from gowaku still gets printed when stricter level is set
```
let log_level = match env::var("WAKU_LOG_LEVEL") {
        Ok(level) => match level.to_uppercase().as_str() {
            "DEBUG" => WakuLogLevel::Debug,
            "INFO" => WakuLogLevel::Info,
            "WARN" => WakuLogLevel::Warn,
            "ERROR" => WakuLogLevel::Error,
            "FATAL" => WakuLogLevel::Fatal,
            "PANIC" => WakuLogLevel::Panic,
            _ => WakuLogLevel::Warn,
        },
        Err(_) => WakuLogLevel::Error,
    };
```

**Comment by hopeyen** [comment]
fixed after the new release, thanks!!
