### ISSUE TITLE
bug: peer count cannot be deserialized

### ISSUE THREAD

**Issue by hopeyen** [waku-org/waku-rust-bindings#72]
Hi there, I am encountering a small bug when running function `waku_peer_count` at https://github.com/waku-org/waku-rust-bindings/blob/master/waku-bindings/src/node/peers.rs#L99

The error is 
```
Err("could not deserialize waku JsonResponse: invalid type: string \"3\", expected usize at line 1 column 13")
```

Which seems like a simple mismatch on types between the go-binding and rust deserialization since rust is expecting an `usize`. 

Reproducible by calling `waku_peer_count()` on a running waku node handle

**Comment by richard-ramos** [comment]
just published v0.3.1! with the fix
